export const SERVICE_TYPES = [
  "IT Support",
  "Web Development",
  "Technical Support",
  "Help Desk Technicians",
];

export const testimonialsData = [
  {
    name: "Sarah Mitchell",
    position: "CTO, InnovateTech Solutions",
    location: "London, UK",
    region: "European",
    service: "Web Development",
    rating: 5,
    testimonial: "Working with Philip was a game-changer for our platform. The Next.js application he built is robust, scalable, and performs exceptionally well. His technical expertise and project management skills ensured timely delivery and exceeded our expectations.",
    projectOutcome: "50% increase in user engagement, 30% faster load times",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    flag: "🇬🇧",
  },
  {
    name: "Marcus Johnson",
    position: "VP Engineering, CloudScale Inc.",
    location: "San Francisco, USA",
    region: "American",
    service: "Technical Support",
    rating: 5,
    testimonial: "Philip's expertise in technical support transformed our CI/CD pipeline and infrastructure. His implementation of monitoring and automation significantly improved our deployment efficiency. A true professional who understands both technical depth and business needs.",
    projectOutcome: "80% faster deployments, 60% reduction in incidents",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    flag: "🇺🇸",
  },
  {
    name: "Jean-Pierre Dubois",
    position: "IT Director, Élan Digital",
    location: "Paris, France",
    region: "European",
    service: "IT Support",
    rating: 5,
    testimonial: "Philip designed and implemented a secure, scalable network infrastructure for our multi-site operations. His expertise in network security and VPN configurations ensured seamless connectivity across all our offices. Professional, reliable, and technically excellent.",
    projectOutcome: "99.9% network uptime, 50% improvement in security posture",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    flag: "🇫🇷",
  },
  {
    name: "Jennifer Martinez",
    position: "Product Manager, SaaS Solutions",
    location: "New York, USA",
    region: "American",
    service: "Web Development",
    rating: 5,
    testimonial: "Philip's work on our React-based SaaS platform was exceptional. He delivered a modern, responsive application that our users love. His ability to balance feature development with performance optimization is remarkable. Looking forward to future collaborations!",
    projectOutcome: "45% increase in user retention, 25% boost in conversions",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    flag: "🇺🇸",
  },
  {
    name: "Amara Diallo",
    position: "Director, DataVantage Africa",
    location: "Nairobi, Kenya",
    region: "African",
    service: "Help Desk Technicians",
    rating: 5,
    testimonial: "Philip set up and trained our help desk team on best practices and ticketing systems. His documentation and escalation procedures reduced resolution time by 40%. Highly recommend for IT support and help desk optimization!",
    projectOutcome: "40% faster ticket resolution, improved customer satisfaction",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    flag: "🇰🇪",
  },
];
